DROP TABLE IF EXISTS PROJECTS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS TASKS CASCADE;

CREATE TABLE PROJECTS
(
  PROJECT_ID serial NOT NULL,
  NAME varchar(50) NOT NULL
);

CREATE TABLE USERS
(
  USER_ID serial NOT NULL,
  FIRST_NAME varchar(30) NOT NULL,
  LAST_NAME varchar(30)
);

CREATE TABLE TASKS
(
  TASK_ID serial NOT NULL,
  NAME varchar(100)	 NOT NULL,
  DESCRIPTION text,
  PRIORITY integer NOT NULL,
  STATUS integer NOT NULL,
  START_DATE date NOT NULL,
  DUE_DATE date,
  ASSIGNEE_ID integer NOT NULL,
  PROJECT_ID integer NOT NULL
);

ALTER TABLE PROJECTS ADD CONSTRAINT PK_PROJECT_ID
PRIMARY KEY (PROJECT_ID);

ALTER TABLE USERS ADD CONSTRAINT PK_USER_ID
PRIMARY KEY (USER_ID);

ALTER TABLE TASKS ADD CONSTRAINT PK_TASK_ID
PRIMARY KEY (TASK_ID);


ALTER TABLE TASKS ADD CONSTRAINT FK_ASSIGNEE
FOREIGN KEY (ASSIGNEE_ID) REFERENCES USERS (USER_ID);

ALTER TABLE TASKS ADD CONSTRAINT FK_PROJECT_ID
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID);
